<script setup>
import { ref } from "vue";
import { useMoviesStore } from "@/stores/counter";
import myFilms from "../components/my-films.vue";
import TheLayout from "../components/TheLayout.vue";

const moviesStore = useMoviesStore();

const getFilms = () => {
    moviesStore.getFilms(filmQuery.value);
};
const filmId = (id) => {
    moviesStore.getFilmId(id);
};

const myFilmsList = [
    {
        id: 839646,
        countries: [{ name: "США" }, { name: "Япония" }],
        facts: [
            {
                value: 'Режиссёрский дебют <a href="/name/1206150/" class="all">Брайана Фи</a>.',
                type: "FACT",
                spoiler: false,
            },
            {
                value: "Имена некоторых персонажей из нового поколения высокотехнологичных гоночных машин являются несколько изменёнными именами актёров озвучивания — Чейса Рэйслотта, к примеру, озвучивает профессиональный гонщик Чейс Эллиот.",
                type: "FACT",
                spoiler: false,
            },
        ],
        genres: [
            { name: "мультфильм" },
            { name: "комедия" },
            { name: "приключения" },
            { name: "семейный" },
            { name: "спорт" },
        ],
        lists: [
            "hd-family",
            "box-usa-all-time",
            "box-russia-dollar",
            "box-world-not-usa",
            "box-total",
        ],
        names: [
            { name: "Тачки 3" },
            { name: "Cars 3" },
            {
                name: "Cars 3 สี่ล้อซิ่ง ชิงบัลลังก์แชมป์",
                language: "TH",
                type: null,
            },
            { name: "카3: 새로운 도전", language: "KR", type: null },
            { name: "Cars 3 - Evolution", language: "DE", type: null },
            { name: "Tachki 3", language: "RU", type: null },
            { name: "反斗車王3", language: "HK", type: null },
            { name: "Autot 3", language: "FI", type: null },
            { name: "Көліктер 3", language: "KZ", type: null },
            { name: "Avtomobili 3", language: "SI", type: null },
            { name: "Maşınlar 3", language: "AZ", type: null },
            { name: "Cars: 3", language: "ES", type: null },
        ],
        persons: [
            {
                id: 9213,
                photo: "https://image.openmoviedb.com/kinopoisk-st-images//actor_iphone/iphone360_9213.jpg",
                name: "Оуэн Уилсон",
                enName: "Owen Wilson",
                description: "Lightning McQueen",
                profession: "актеры",
                enProfession: "actor",
            },
            {
                id: 1688440,
                photo: "https://image.openmoviedb.com/kinopoisk-st-images//actor_iphone/iphone360_1688440.jpg",
                name: "Кристела Алонсо",
                enName: "Cristela Alonzo",
                description: "Cruz Ramirez",
                profession: "актеры",
                enProfession: "actor",
            },
            {
                id: 6145,
                photo: "https://image.openmoviedb.com/kinopoisk-st-images//actor_iphone/iphone360_6145.jpg",
                name: "Крис Купер",
                enName: "Chris Cooper",
                description: "Smokey",
                profession: "актеры",
                enProfession: "actor",
            },
            {
                id: 14851,
                photo: "https://image.openmoviedb.com/kinopoisk-st-images//actor_iphone/iphone360_14851.jpg",
                name: "Нэйтан Филлион",
                enName: "Nathan Fillion",
                description: "Sterling",
                profession: "актеры",
                enProfession: "actor",
            },
            {
                id: 476619,
                photo: "https://image.openmoviedb.com/kinopoisk-st-images//actor_iphone/iphone360_476619.jpg",
                name: "Ларри-кабельщик",
                enName: "Larry the Cable Guy",
                description: "Mater",
                profession: "актеры",
                enProfession: "actor",
            },
            {
                id: 1121926,
                photo: "https://image.openmoviedb.com/kinopoisk-st-images//actor_iphone/iphone360_1121926.jpg",
                name: "Арми Хаммер",
                enName: "Armie Hammer",
                description: "Jackson Storm",
                profession: "актеры",
                enProfession: "actor",
            },
            {
                id: 964639,
                photo: "https://image.openmoviedb.com/kinopoisk-st-images//actor_iphone/iphone360_964639.jpg",
                name: "Рэй Мальоцци",
                enName: "Ray Magliozzi",
                description: "Dusty",
                profession: "актеры",
                enProfession: "actor",
            },
            {
                id: 25491,
                photo: "https://image.openmoviedb.com/kinopoisk-st-images//actor_iphone/iphone360_25491.jpg",
                name: "Тони Шэлуб",
                enName: "Tony Shalhoub",
                description: "Luigi",
                profession: "актеры",
                enProfession: "actor",
            },
            {
                id: 22527,
                photo: "https://image.openmoviedb.com/kinopoisk-st-images//actor_iphone/iphone360_22527.jpg",
                name: "Бонни Хант",
                enName: "Bonnie Hunt",
                description: "Sally",
                profession: "актеры",
                enProfession: "actor",
            },
            {
                id: 81765,
                photo: "https://image.openmoviedb.com/kinopoisk-st-images//actor_iphone/iphone360_81765.jpg",
                name: "Лиа ДеЛария",
                enName: "Lea DeLaria",
                description: "Miss Fritter",
                profession: "актеры",
                enProfession: "actor",
            },
            {
                id: 151423,
                photo: "https://image.openmoviedb.com/kinopoisk-st-images//actor_iphone/iphone360_151423.jpg",
                name: "Рэнди Ньюман",
                enName: "Randy Newman",
                description: null,
                profession: "композиторы",
                enProfession: "composer",
            },
            {
                id: 4045292,
                photo: "https://image.openmoviedb.com/kinopoisk-st-images//actor_iphone/iphone360_4045292.jpg",
                name: "Берт Берри",
                enName: "Bert Berry",
                description: null,
                profession: "художники",
                enProfession: "designer",
            },
            {
                id: 2472027,
                photo: "https://image.openmoviedb.com/kinopoisk-st-images//actor_iphone/iphone360_2472027.jpg",
                name: "Крэйг Фостер",
                enName: "Craig Foster",
                description: null,
                profession: "художники",
                enProfession: "designer",
            },
            {
                id: 5228897,
                photo: "https://image.openmoviedb.com/kinopoisk-st-images//actor_iphone/iphone360_5228897.jpg",
                name: "Ной Клочек",
                enName: "Noah Klocek",
                description: null,
                profession: "художники",
                enProfession: "designer",
            },
            {
                id: 5052825,
                photo: "https://image.openmoviedb.com/kinopoisk-st-images//actor_iphone/iphone360_5052825.jpg",
                name: "Лора Филлипс",
                enName: "Laura Phillips",
                description: null,
                profession: "художники",
                enProfession: "designer",
            },
            {
                id: 1206150,
                photo: "https://image.openmoviedb.com/kinopoisk-st-images//actor_iphone/iphone360_1206150.jpg",
                name: "Брайан Фи",
                enName: "Brian Fee",
                description: null,
                profession: "режиссеры",
                enProfession: "director",
            },
            {
                id: 2769695,
                photo: "https://image.openmoviedb.com/kinopoisk-st-images//actor_iphone/iphone360_2769695.jpg",
                name: "Джейсон Худак",
                enName: "Jason Hudak",
                description: null,
                profession: "монтажеры",
                enProfession: "editor",
            },
            {
                id: 23948,
                photo: "https://image.openmoviedb.com/kinopoisk-st-images//actor_iphone/iphone360_23948.jpg",
                name: "Джон Лассетер",
                enName: "John Lasseter",
                description: null,
                profession: "продюсеры",
                enProfession: "producer",
            },
            {
                id: 65221,
                photo: "https://image.openmoviedb.com/kinopoisk-st-images//actor_iphone/iphone360_65221.jpg",
                name: "Кевин Реэр",
                enName: "Kevin Reher",
                description: null,
                profession: "продюсеры",
                enProfession: "producer",
            },
            {
                id: 3706838,
                photo: "https://image.openmoviedb.com/kinopoisk-st-images//actor_iphone/iphone360_3706838.jpg",
                name: "Андреа Уоррен",
                enName: "Andrea Warren",
                description: null,
                profession: "продюсеры",
                enProfession: "producer",
            },
            {
                id: 231553,
                photo: "https://image.openmoviedb.com/kinopoisk-st-images//actor_iphone/iphone360_231553.jpg",
                name: "Дмитрий Харатьян",
                enName: null,
                description: null,
                profession: "актеры дубляжа",
                enProfession: "voice_actor",
            },
            {
                id: 464050,
                photo: "https://image.openmoviedb.com/kinopoisk-st-images//actor_iphone/iphone360_464050.jpg",
                name: "Ирина Пегова",
                enName: null,
                description: null,
                profession: "актеры дубляжа",
                enProfession: "voice_actor",
            },
            {
                id: 325814,
                photo: "https://image.openmoviedb.com/kinopoisk-st-images//actor_iphone/iphone360_325814.jpg",
                name: "Рудольф Панков",
                enName: null,
                description: null,
                profession: "актеры дубляжа",
                enProfession: "voice_actor",
            },
            {
                id: 1459799,
                photo: "https://image.openmoviedb.com/kinopoisk-st-images//actor_iphone/iphone360_1459799.jpg",
                name: "Станислав Стрелков",
                enName: null,
                description: null,
                profession: "актеры дубляжа",
                enProfession: "voice_actor",
            },
            {
                id: 261736,
                photo: "https://image.openmoviedb.com/kinopoisk-st-images//actor_iphone/iphone360_261736.jpg",
                name: "Сергей Кузнецов",
                enName: null,
                description: null,
                profession: "актеры дубляжа",
                enProfession: "voice_actor",
            },
            {
                id: 1105216,
                photo: "https://image.openmoviedb.com/kinopoisk-st-images//actor_iphone/iphone360_1105216.jpg",
                name: "Кил Мюррэй",
                enName: "Kiel Murray",
                description: null,
                profession: "сценаристы",
                enProfession: "writer",
            },
            {
                id: 32470,
                photo: "https://image.openmoviedb.com/kinopoisk-st-images//actor_iphone/iphone360_32470.jpg",
                name: "Боб Питерсон",
                enName: "Bob Peterson",
                description: null,
                profession: "сценаристы",
                enProfession: "writer",
            },
            {
                id: 7779,
                photo: "https://image.openmoviedb.com/kinopoisk-st-images//actor_iphone/iphone360_7779.jpg",
                name: "Майк Рич",
                enName: "Mike Rich",
                description: null,
                profession: "сценаристы",
                enProfession: "writer",
            },
            {
                id: 1206150,
                photo: "https://image.openmoviedb.com/kinopoisk-st-images//actor_iphone/iphone360_1206150.jpg",
                name: "Брайан Фи",
                enName: "Brian Fee",
                description: null,
                profession: "сценаристы",
                enProfession: "writer",
            },
            {
                id: 17932,
                photo: "https://image.openmoviedb.com/kinopoisk-st-images//actor_iphone/iphone360_17932.jpg",
                name: "Керри Вашингтон",
                enName: "Kerry Washington",
                description: null,
                profession: "актеры",
                enProfession: "actor",
            },
            {
                id: 3178,
                photo: "https://image.openmoviedb.com/kinopoisk-st-images//actor_iphone/iphone360_3178.jpg",
                name: "Боб Костас",
                enName: "Bob Costas",
                description: null,
                profession: "актеры",
                enProfession: "actor",
            },
            {
                id: 10785,
                photo: "https://image.openmoviedb.com/kinopoisk-st-images//actor_iphone/iphone360_10785.jpg",
                name: "Марго Мартиндейл",
                enName: "Margo Martindale",
                description: null,
                profession: "актеры",
                enProfession: "actor",
            },
            {
                id: 540460,
                photo: "https://image.openmoviedb.com/kinopoisk-st-images//actor_iphone/iphone360_540460.jpg",
                name: "Даррел Уалтрип",
                enName: "Darrell Waltrip",
                description: null,
                profession: "актеры",
                enProfession: "actor",
            },
            {
                id: 29846,
                photo: "https://image.openmoviedb.com/kinopoisk-st-images//actor_iphone/iphone360_29846.jpg",
                name: "Исайя Уитлок мл.",
                enName: "Isiah Whitlock Jr.",
                description: null,
                profession: "актеры",
                enProfession: "actor",
            },
            {
                id: 50565,
                photo: "https://image.openmoviedb.com/kinopoisk-st-images//actor_iphone/iphone360_50565.jpg",
                name: "Гуидо Куарони",
                enName: "Guido Quaroni",
                description: null,
                profession: "актеры",
                enProfession: "actor",
            },
            {
                id: 964640,
                photo: "https://image.openmoviedb.com/kinopoisk-st-images//actor_iphone/iphone360_964640.jpg",
                name: "Том Мальоцци",
                enName: "Tom Magliozzi",
                description: null,
                profession: "актеры",
                enProfession: "actor",
            },
            {
                id: 13821,
                photo: "https://image.openmoviedb.com/kinopoisk-st-images//actor_iphone/iphone360_13821.jpg",
                name: "Джон Ратценбергер",
                enName: "John Ratzenberger",
                description: null,
                profession: "актеры",
                enProfession: "actor",
            },
            {
                id: 162050,
                photo: "https://image.openmoviedb.com/kinopoisk-st-images//actor_iphone/iphone360_162050.jpg",
                name: "Кайл Петти",
                enName: "Kyle Petty",
                description: null,
                profession: "актеры",
                enProfession: "actor",
            },
            {
                id: 1647265,
                photo: "https://image.openmoviedb.com/kinopoisk-st-images//actor_iphone/iphone360_1647265.jpg",
                name: "Льюис Хэмилтон",
                enName: "Lewis Hamilton",
                description: null,
                profession: "актеры",
                enProfession: "actor",
            },
            {
                id: 228457,
                photo: "https://image.openmoviedb.com/kinopoisk-st-images//actor_iphone/iphone360_228457.jpg",
                name: "Ллойд Шерр",
                enName: "Lloyd Sherr",
                description: null,
                profession: "актеры",
                enProfession: "actor",
            },
            {
                id: 540151,
                photo: "https://image.openmoviedb.com/kinopoisk-st-images//actor_iphone/iphone360_540151.jpg",
                name: "Джуниор Джонсон",
                enName: "Junior Johnson",
                description: null,
                profession: "актеры",
                enProfession: "actor",
            },
            {
                id: 3414865,
                photo: "https://image.openmoviedb.com/kinopoisk-st-images//actor_iphone/iphone360_3414865.jpg",
                name: "Рэй Эвернэм",
                enName: "Ray Evernham",
                description: null,
                profession: "актеры",
                enProfession: "actor",
            },
            {
                id: 11862,
                photo: "https://image.openmoviedb.com/kinopoisk-st-images//actor_iphone/iphone360_11862.jpg",
                name: "Пол Ньюман",
                enName: "Paul Newman",
                description: null,
                profession: "актеры",
                enProfession: "actor",
            },
            {
                id: 12722,
                photo: "https://image.openmoviedb.com/kinopoisk-st-images//actor_iphone/iphone360_12722.jpg",
                name: "Чич Марин",
                enName: "Cheech Marin",
                description: null,
                profession: "актеры",
                enProfession: "actor",
            },
            {
                id: 296529,
                photo: "https://image.openmoviedb.com/kinopoisk-st-images//actor_iphone/iphone360_296529.jpg",
                name: "Х.А. «Хампи» Уилер",
                enName: "H.A. «Humpy» Wheeler",
                description: null,
                profession: "актеры",
                enProfession: "actor",
            },
            {
                id: 63746,
                photo: "https://image.openmoviedb.com/kinopoisk-st-images//actor_iphone/iphone360_63746.jpg",
                name: "Кэтрин Хелмонд",
                enName: "Katherine Helmond",
                description: null,
                profession: "актеры",
                enProfession: "actor",
            },
            {
                id: 21824,
                photo: "https://image.openmoviedb.com/kinopoisk-st-images//actor_iphone/iphone360_21824.jpg",
                name: "Пол Дули",
                enName: "Paul Dooley",
                description: null,
                profession: "актеры",
                enProfession: "actor",
            },
            {
                id: 9194,
                photo: "https://image.openmoviedb.com/kinopoisk-st-images//actor_iphone/iphone360_9194.jpg",
                name: "Дженифер Льюис",
                enName: "Jenifer Lewis",
                description: null,
                profession: "актеры",
                enProfession: "actor",
            },
            {
                id: 1545701,
                photo: "https://image.openmoviedb.com/kinopoisk-st-images//actor_iphone/iphone360_1545701.jpg",
                name: "Шеннон Спейк",
                enName: "Shannon Spake",
                description: null,
                profession: "актеры",
                enProfession: "actor",
            },
            {
                id: 3666942,
                photo: "https://image.openmoviedb.com/kinopoisk-st-images//actor_iphone/iphone360_3666942.jpg",
                name: "Мадлен Макгроу",
                enName: "Madeleine McGraw",
                description: null,
                profession: "актеры",
                enProfession: "actor",
            },
            {
                id: 1083444,
                photo: "https://image.openmoviedb.com/kinopoisk-st-images//actor_iphone/iphone360_1083444.jpg",
                name: "Майкл Уоллис",
                enName: "Michael Wallis",
                description: null,
                profession: "актеры",
                enProfession: "actor",
            },
            {
                id: 568031,
                photo: "https://image.openmoviedb.com/kinopoisk-st-images//actor_iphone/iphone360_568031.jpg",
                name: "Майк Джой",
                enName: "Mike Joy",
                description: null,
                profession: "актеры",
                enProfession: "actor",
            },
            {
                id: 32989,
                photo: "https://image.openmoviedb.com/kinopoisk-st-images//actor_iphone/iphone360_32989.jpg",
                name: "Джефф Гордон",
                enName: "Jeff Gordon",
                description: null,
                profession: "актеры",
                enProfession: "actor",
            },
            {
                id: 4727859,
                photo: "https://image.openmoviedb.com/kinopoisk-st-images//actor_iphone/iphone360_4727859.jpg",
                name: "Дэниэл Суарес",
                enName: "Daniel Suarez",
                description: null,
                profession: "актеры",
                enProfession: "actor",
            },
            {
                id: 4529568,
                photo: "https://image.openmoviedb.com/kinopoisk-st-images//actor_iphone/iphone360_4529568.jpg",
                name: "Райан Блэйни",
                enName: "Ryan Blaney",
                description: null,
                profession: "актеры",
                enProfession: "actor",
            },
            {
                id: 3933029,
                photo: "https://image.openmoviedb.com/kinopoisk-st-images//actor_iphone/iphone360_3933029.jpg",
                name: "Даррел Уоллес мл.",
                enName: "Darrell Wallace Jr.",
                description: null,
                profession: "актеры",
                enProfession: "actor",
            },
            {
                id: 3558188,
                photo: "https://image.openmoviedb.com/kinopoisk-st-images//actor_iphone/iphone360_3558188.jpg",
                name: "Чейз Эллиотт",
                enName: "Chase Elliott",
                description: null,
                profession: "актеры",
                enProfession: "actor",
            },
            {
                id: 128717,
                photo: "https://image.openmoviedb.com/kinopoisk-st-images//actor_iphone/iphone360_128717.jpg",
                name: "Ричард Петти",
                enName: "Richard Petty",
                description: null,
                profession: "актеры",
                enProfession: "actor",
            },
            {
                id: 4173614,
                photo: "https://image.openmoviedb.com/kinopoisk-st-images//actor_iphone/iphone360_4173614.jpg",
                name: "Андра Дэй",
                enName: "Andra Day",
                description: null,
                profession: "актеры",
                enProfession: "actor",
            },
            {
                id: 55469,
                photo: "https://image.openmoviedb.com/kinopoisk-st-images//actor_iphone/iphone360_55469.jpg",
                name: "Джереми Максвелл",
                enName: "Jeremy Maxwell",
                description: null,
                profession: "актеры",
                enProfession: "actor",
            },
            {
                id: 605024,
                photo: "https://image.openmoviedb.com/kinopoisk-st-images//actor_iphone/iphone360_605024.jpg",
                name: "А.Дж. Рибли III",
                enName: "A.J. Riebli III",
                description: null,
                profession: "актеры",
                enProfession: "actor",
            },
            {
                id: 1741502,
                photo: "https://image.openmoviedb.com/kinopoisk-st-images//actor_iphone/iphone360_1741502.jpg",
                name: "Уильям Коун",
                enName: "William Cone",
                description: null,
                profession: "художники",
                enProfession: "designer",
            },
            {
                id: 2405711,
                photo: "https://image.openmoviedb.com/kinopoisk-st-images//actor_iphone/iphone360_2405711.jpg",
                name: "Джей Шустер",
                enName: "Jay Shuster",
                description: null,
                profession: "художники",
                enProfession: "designer",
            },
            {
                id: 2704915,
                photo: "https://image.openmoviedb.com/kinopoisk-st-images//actor_iphone/iphone360_2704915.jpg",
                name: "Виктор Хориняк",
                enName: null,
                description: null,
                profession: "актеры дубляжа",
                enProfession: "voice_actor",
            },
            {
                id: 261729,
                photo: "https://image.openmoviedb.com/kinopoisk-st-images//actor_iphone/iphone360_261729.jpg",
                name: "Владимир Антоник",
                enName: null,
                description: null,
                profession: "актеры дубляжа",
                enProfession: "voice_actor",
            },
            {
                id: 543036,
                photo: "https://image.openmoviedb.com/kinopoisk-st-images//actor_iphone/iphone360_543036.jpg",
                name: "Сергей Бызгу",
                enName: null,
                description: null,
                profession: "актеры дубляжа",
                enProfession: "voice_actor",
            },
            {
                id: 251183,
                photo: "https://image.openmoviedb.com/kinopoisk-st-images//actor_iphone/iphone360_251183.jpg",
                name: "Алика Смехова",
                enName: null,
                description: null,
                profession: "актеры дубляжа",
                enProfession: "voice_actor",
            },
            {
                id: 1654784,
                photo: "https://image.openmoviedb.com/kinopoisk-st-images//actor_iphone/iphone360_1654784.jpg",
                name: "Елена Терновая",
                enName: null,
                description: null,
                profession: "актеры дубляжа",
                enProfession: "voice_actor",
            },
            {
                id: 4077591,
                photo: "https://image.openmoviedb.com/kinopoisk-st-images//actor_iphone/iphone360_4077591.jpg",
                name: "Елена Летучая",
                enName: null,
                description: null,
                profession: "актеры дубляжа",
                enProfession: "voice_actor",
            },
            {
                id: 1671811,
                photo: "https://image.openmoviedb.com/kinopoisk-st-images//actor_iphone/iphone360_1671811.jpg",
                name: "Михаил Захаров",
                enName: null,
                description: null,
                profession: "актеры дубляжа",
                enProfession: "voice_actor",
            },
            {
                id: 327441,
                photo: "https://image.openmoviedb.com/kinopoisk-st-images//actor_iphone/iphone360_327441.jpg",
                name: "Ирина Гришина",
                enName: null,
                description: null,
                profession: "актеры дубляжа",
                enProfession: "voice_actor",
            },
            {
                id: 1671810,
                photo: "https://image.openmoviedb.com/kinopoisk-st-images//actor_iphone/iphone360_1671810.jpg",
                name: "Михаил Брагин",
                enName: null,
                description: null,
                profession: "актеры дубляжа",
                enProfession: "voice_actor",
            },
            {
                id: 2956583,
                photo: "https://image.openmoviedb.com/kinopoisk-st-images//actor_iphone/iphone360_2956583.jpg",
                name: "Владимир Левашёв",
                enName: null,
                description: null,
                profession: "актеры дубляжа",
                enProfession: "voice_actor",
            },
            {
                id: 37392,
                photo: "https://image.openmoviedb.com/kinopoisk-st-images//actor_iphone/iphone360_37392.jpg",
                name: "Максим Сергеев",
                enName: null,
                description: null,
                profession: "актеры дубляжа",
                enProfession: "voice_actor",
            },
            {
                id: 2534603,
                photo: "https://image.openmoviedb.com/kinopoisk-st-images//actor_iphone/iphone360_2534603.jpg",
                name: "Нанни Бальдини",
                enName: "Nanni Baldini",
                description: null,
                profession: "актеры дубляжа",
                enProfession: "voice_actor",
            },
            {
                id: 1948766,
                photo: "https://image.openmoviedb.com/kinopoisk-st-images//actor_iphone/iphone360_1948766.jpg",
                name: "Денис Некрасов",
                enName: null,
                description: null,
                profession: "актеры дубляжа",
                enProfession: "voice_actor",
            },
            {
                id: 373163,
                photo: "https://image.openmoviedb.com/kinopoisk-st-images//actor_iphone/iphone360_373163.jpg",
                name: "Александр Черкашин",
                enName: null,
                description: null,
                profession: "актеры дубляжа",
                enProfession: "voice_actor",
            },
            {
                id: 1660134,
                photo: "https://image.openmoviedb.com/kinopoisk-st-images//actor_iphone/iphone360_1660134.jpg",
                name: "Михаил Хрусталёв",
                enName: null,
                description: null,
                profession: "актеры дубляжа",
                enProfession: "voice_actor",
            },
            {
                id: 37419,
                photo: "https://image.openmoviedb.com/kinopoisk-st-images//actor_iphone/iphone360_37419.jpg",
                name: "Александр Разбаш",
                enName: null,
                description: null,
                profession: "актеры дубляжа",
                enProfession: "voice_actor",
            },
            {
                id: 1823794,
                photo: "https://image.openmoviedb.com/kinopoisk-st-images//actor_iphone/iphone360_1823794.jpg",
                name: "Алексей Макрецкий",
                enName: null,
                description: null,
                profession: "актеры дубляжа",
                enProfession: "voice_actor",
            },
            {
                id: 1230514,
                photo: "https://image.openmoviedb.com/kinopoisk-st-images//actor_iphone/iphone360_1230514.jpg",
                name: "Артемий Веселов",
                enName: null,
                description: null,
                profession: "актеры дубляжа",
                enProfession: "voice_actor",
            },
            {
                id: 127995,
                photo: "https://image.openmoviedb.com/kinopoisk-st-images//actor_iphone/iphone360_127995.jpg",
                name: "Армен Джигарханян",
                enName: null,
                description: null,
                profession: "актеры дубляжа",
                enProfession: "voice_actor",
            },
            {
                id: 1896146,
                photo: "https://image.openmoviedb.com/kinopoisk-st-images//actor_iphone/iphone360_1896146.jpg",
                name: "Андрей Мошков",
                enName: null,
                description: null,
                profession: "актеры дубляжа",
                enProfession: "voice_actor",
            },
            {
                id: 1796421,
                photo: "https://image.openmoviedb.com/kinopoisk-st-images//actor_iphone/iphone360_1796421.jpg",
                name: "Ирина Балай",
                enName: null,
                description: null,
                profession: "актеры дубляжа",
                enProfession: "voice_actor",
            },
            {
                id: 637310,
                photo: "https://image.openmoviedb.com/kinopoisk-st-images//actor_iphone/iphone360_637310.jpg",
                name: "Борис Хасанов",
                enName: null,
                description: null,
                profession: "актеры дубляжа",
                enProfession: "voice_actor",
            },
            {
                id: 2459512,
                photo: "https://image.openmoviedb.com/kinopoisk-st-images//actor_iphone/iphone360_2459512.jpg",
                name: "Татьяна Гордеева",
                enName: null,
                description: null,
                profession: "актеры дубляжа",
                enProfession: "voice_actor",
            },
            {
                id: 4734204,
                photo: "https://image.openmoviedb.com/kinopoisk-st-images//actor_iphone/iphone360_4734204.jpg",
                name: "Степан Донской",
                enName: null,
                description: null,
                profession: "актеры дубляжа",
                enProfession: "voice_actor",
            },
            {
                id: 298501,
                photo: "https://image.openmoviedb.com/kinopoisk-st-images//actor_iphone/iphone360_298501.jpg",
                name: "Николай Федорцов",
                enName: null,
                description: null,
                profession: "актеры дубляжа",
                enProfession: "voice_actor",
            },
            {
                id: 1761770,
                photo: "https://image.openmoviedb.com/kinopoisk-st-images//actor_iphone/iphone360_1761770.jpg",
                name: "Артем Бордовский",
                enName: null,
                description: null,
                profession: "актеры дубляжа",
                enProfession: "voice_actor",
            },
            {
                id: 1230517,
                photo: "https://image.openmoviedb.com/kinopoisk-st-images//actor_iphone/iphone360_1230517.jpg",
                name: "Вадим Бурлаков",
                enName: null,
                description: null,
                profession: "актеры дубляжа",
                enProfession: "voice_actor",
            },
            {
                id: 4362284,
                photo: "https://image.openmoviedb.com/kinopoisk-st-images//actor_iphone/iphone360_4362284.jpg",
                name: "Анастасия Слепченко",
                enName: null,
                description: null,
                profession: "актеры дубляжа",
                enProfession: "voice_actor",
            },
            {
                id: 477449,
                photo: "https://image.openmoviedb.com/kinopoisk-st-images//actor_iphone/iphone360_477449.jpg",
                name: "Елена Шульман",
                enName: null,
                description: null,
                profession: "актеры дубляжа",
                enProfession: "voice_actor",
            },
            {
                id: 1761814,
                photo: "https://image.openmoviedb.com/kinopoisk-st-images//actor_iphone/iphone360_1761814.jpg",
                name: "Алексей Черных",
                enName: null,
                description: null,
                profession: "актеры дубляжа",
                enProfession: "voice_actor",
            },
            {
                id: 2333066,
                photo: "https://image.openmoviedb.com/kinopoisk-st-images//actor_iphone/iphone360_2333066.jpg",
                name: "Сергей Куницкий",
                enName: null,
                description: null,
                profession: "актеры дубляжа",
                enProfession: "voice_actor",
            },
            {
                id: 2857737,
                photo: "https://image.openmoviedb.com/kinopoisk-st-images//actor_iphone/iphone360_2857737.jpg",
                name: "Сергей Усков",
                enName: null,
                description: null,
                profession: "актеры дубляжа",
                enProfession: "voice_actor",
            },
            {
                id: 3704185,
                photo: "https://image.openmoviedb.com/kinopoisk-st-images//actor_iphone/iphone360_3704185.jpg",
                name: "Анна Киселёва",
                enName: null,
                description: null,
                profession: "актеры дубляжа",
                enProfession: "voice_actor",
            },
        ],
        productionCompanies: [
            {
                name: "Pixar",
                url: "https://www.themoviedb.org/t/p/original/1TjvGVDMYsj6JBxOAkUHpPEwLf7.png",
                previewUrl:
                    "https://www.themoviedb.org/t/p/w500/1TjvGVDMYsj6JBxOAkUHpPEwLf7.png",
            },
        ],
        seasonsInfo: [],
        spokenLanguages: [{ name: "English", nameEn: "English" }],
        alternativeName: "Cars 3",
        backdrop: {
            url: "https://image.openmoviedb.com/kinopoisk-ott-images/212840/2a00000178c5bb06e103e74004226646f0bc/orig",
            previewUrl:
                "https://image.openmoviedb.com/kinopoisk-ott-images/212840/2a00000178c5bb06e103e74004226646f0bc/x1000",
        },
        budget: { value: 175000000, currency: "$" },
        description:
            "Встречайте самого знаменитого гонщика всех времен, легенду гоночного трека Молнию Маккуина!\n\nГерой все еще продолжает показывать лучшие результаты на всех турнирах, однако победы даются ему не так легко, а конкуренция становится все жестче. Молнию Маккуина ждут захватывающие приключения, где он встретит новых друзей, а также поймет, что не только скорость и мощность мотора делают гонщика чемпионом.",
        distributors: { distributor: "WDSSPR", distributorRelease: null },
        enName: null,
        externalId: {
            imdb: "tt3606752",
            tmdb: 260514,
            kpHD: "4a87d4a16c400dfc8476d76933b85f1b",
        },
        images: { framesCount: 8 },
        movieLength: 103,
        name: "Тачки 3",
        networks: null,
        poster: {
            url: "https://image.openmoviedb.com/kinopoisk-images/1946459/c5fedf26-8e3b-4ad0-8f1a-3d213212b686/orig",
            previewUrl:
                "https://image.openmoviedb.com/kinopoisk-images/1946459/c5fedf26-8e3b-4ad0-8f1a-3d213212b686/x1000",
        },
        premiere: {
            world: "2017-06-10T00:00:00.000Z",
            russia: "2017-06-15T00:00:00.000Z",
            digital: "2017-10-23T00:00:00.000Z",
            bluray: null,
            cinema: null,
            dvd: null,
        },
        rating: {
            kp: 7.276,
            imdb: 6.7,
            filmCritics: 6.1,
            russianFilmCritics: 87.5,
            await: null,
        },
        slogan: "Гонка продолжается, пока сверкает молния",
        status: null,
        subType: null,
        votes: {
            kp: 186758,
            imdb: 124582,
            filmCritics: 233,
            russianFilmCritics: 8,
            await: 0,
        },
        year: 2017,
        ageRating: 6,
        ratingMpaa: "g",
        updatedAt: "2024-09-08T00:01:28.010Z",
        imagesInfo: { framesCount: 8 },
        sequelsAndPrequels: [
            {
                id: 61249,
                name: "Тачки",
                alternativeName: "Cars",
                enName: null,
                type: "cartoon",
                poster: {
                    url: "https://image.openmoviedb.com/kinopoisk-images/1773646/28842f10-7eeb-46c4-938e-02182b147172/orig",
                    previewUrl:
                        "https://image.openmoviedb.com/kinopoisk-images/1773646/28842f10-7eeb-46c4-938e-02182b147172/x1000",
                },
                rating: {
                    kp: 7.514,
                    imdb: 7.2,
                    filmCritics: 6.9,
                    russianFilmCritics: 66.6667,
                    await: null,
                },
                year: 2006,
            },
            {
                id: 490462,
                name: "Мультачки: Байки Мэтра",
                alternativeName: "Mater's Tall Tales",
                enName: null,
                type: "animated-series",
                poster: {
                    url: "https://image.openmoviedb.com/kinopoisk-images/1599028/fed5bf06-a5b6-458c-bc44-6af815fcbd3a/orig",
                    previewUrl:
                        "https://image.openmoviedb.com/kinopoisk-images/1599028/fed5bf06-a5b6-458c-bc44-6af815fcbd3a/x1000",
                },
                rating: {
                    kp: 7.065,
                    imdb: 6.8,
                    filmCritics: 0,
                    russianFilmCritics: 0,
                    await: null,
                },
                year: 2008,
            },
            {
                id: 409013,
                name: "Тачки 2",
                alternativeName: "Cars 2",
                enName: null,
                type: "cartoon",
                poster: {
                    url: "https://image.openmoviedb.com/kinopoisk-images/1629390/15e949f7-6809-411e-92cc-cd4e21cf0b8a/orig",
                    previewUrl:
                        "https://image.openmoviedb.com/kinopoisk-images/1629390/15e949f7-6809-411e-92cc-cd4e21cf0b8a/x1000",
                },
                rating: {
                    kp: 6.817,
                    imdb: 6.2,
                    filmCritics: 5.5,
                    russianFilmCritics: 0,
                    await: null,
                },
                year: 2011,
            },
            {
                id: 1370469,
                name: "Тачки на дороге",
                alternativeName: "Cars on the Road",
                enName: null,
                type: "animated-series",
                poster: {
                    url: "https://image.openmoviedb.com/kinopoisk-images/4303601/9f898e13-54dd-4498-b154-a6e3acd17ab9/orig",
                    previewUrl:
                        "https://image.openmoviedb.com/kinopoisk-images/4303601/9f898e13-54dd-4498-b154-a6e3acd17ab9/x1000",
                },
                rating: {
                    kp: 6.657,
                    imdb: 6.9,
                    filmCritics: 0,
                    russianFilmCritics: 0,
                    await: null,
                },
                year: 2022,
            },
        ],
        similarMovies: [
            {
                id: 592300,
                name: "Самолеты",
                enName: null,
                alternativeName: "Planes",
                type: "cartoon",
                poster: {
                    url: "https://avatars.mds.yandex.net/get-kinopoisk-image/4303601/2b816648-b930-455b-8828-b68546735e1a/orig",
                    previewUrl:
                        "https://avatars.mds.yandex.net/get-kinopoisk-image/4303601/2b816648-b930-455b-8828-b68546735e1a/x1000",
                },
                year: 2013,
                rating: {
                    kp: 6.581,
                    imdb: 5.7,
                    filmCritics: 4.6,
                    russianFilmCritics: 33.3333,
                    await: null,
                },
            },
            {
                id: 581651,
                name: "Турбо",
                enName: null,
                alternativeName: "Turbo",
                type: "cartoon",
                poster: {
                    url: "https://avatars.mds.yandex.net/get-kinopoisk-image/1704946/9ea2148c-19e5-405f-81a2-28f1adc6e35d/orig",
                    previewUrl:
                        "https://avatars.mds.yandex.net/get-kinopoisk-image/1704946/9ea2148c-19e5-405f-81a2-28f1adc6e35d/x1000",
                },
                year: 2013,
                rating: {
                    kp: 6.795,
                    imdb: 6.4,
                    filmCritics: 6.1,
                    russianFilmCritics: 66.6667,
                    await: null,
                },
            },
            {
                id: 769220,
                name: "Самолеты: Огонь и вода",
                enName: null,
                alternativeName: "Planes: Fire and Rescue",
                type: "cartoon",
                poster: {
                    url: "https://avatars.mds.yandex.net/get-kinopoisk-image/6201401/1fdc0cf5-a63f-488a-a02b-98bc3e334cf5/orig",
                    previewUrl:
                        "https://avatars.mds.yandex.net/get-kinopoisk-image/6201401/1fdc0cf5-a63f-488a-a02b-98bc3e334cf5/x1000",
                },
                year: 2014,
                rating: {
                    kp: 6.625,
                    imdb: 5.9,
                    filmCritics: 5.2,
                    russianFilmCritics: 66.6667,
                    await: null,
                },
            },
        ],
        fees: {
            world: { value: 383930656, currency: "$" },
            russia: { value: 10784524, currency: "$" },
            usa: { value: 152901115, currency: "$" },
        },
        shortDescription:
            "Легендарному МакКуину предстоит доказать, что он не устарел. Его ждет схватка с тачками нового поколения",
        technology: { hasImax: false, has3D: true },
        ticketsOnSale: false,
        type: "cartoon",
        logo: {
            url: "https://avatars.mds.yandex.net/get-ott/374297/2a00000178c5bbab94e544acfca32428443d/orig",
        },
        typeNumber: 3,
        watchability: { items: [] },
        top10: null,
        top250: null,
        deletedAt: null,
        isSeries: false,
        seriesLength: null,
        totalSeriesLength: null,
        videos: {
            trailers: [
                {
                    url: "https://www.youtube.com/embed/tHlpgQJOSt0",
                    name: "Тачки 3 - Trailer",
                    site: "youtube",
                    type: "TRAILER",
                },
                {
                    url: "https://www.youtube.com/embed/tHlpgQJOSt0",
                    name: "Тачки 3 - Trailer",
                    site: "youtube",
                    type: "TRAILER",
                },
                {
                    url: "https://www.youtube.com/embed/ZuaseSovWDY",
                    name: 'Cars 3 "Rivalry" Official Trailer',
                    site: "youtube",
                    type: "TRAILER",
                },
                {
                    url: "https://www.youtube.com/embed/2LeOH9AGJQM",
                    name: "Cars 3 - Official US Trailer",
                    site: "youtube",
                    type: "TRAILER",
                },
            ],
        },
        isWatch: true,
    },
];
// console.log(myFilmsList);
</script>

<template>
    <the-layout>
        <my-films :films="moviesStore.favorFilms"></my-films>
    </the-layout>
</template>
